### PR TITLE
Test comments looping back from GitHub

### PR DESCRIPTION
**Pull request by rudymatela**
Test comments looping back from GitHub.

Whenever Hoff posts a comment on GitHub, it is notified back by GitHub that that a new comment has been posted.  This makes it so that a test now has this behaviour.

This would have detected the issue with [v0.25.7](https://github.com/channable/hoff/tree/v0.25.7) where Hoff got stuck in an infinite loop.  Please see #140 which applies these tests on top of the buggy version.

### CODE REVIEW

**Review by alex-mckenna — APPROVED** [review]
Looks good to me, good idea to run it through CI with the known failing version :+1:

**Review by ReinierMaas — APPROVED** [review]
LGTM! Thanks for adding this test case and displaying the failure on the buggy version.

**Comment by rudymatela** [comment]
@alex-mckenna @ReinierMaas, thanks for the review.

@OpsBotPrime merge on Friday

**Comment by OpsBotPrime** [comment]
Pull request approved for merge by @rudymatela, rebasing now.

**Comment by OpsBotPrime** [comment]
Rebased as 9af294a0c387945043799f5a099415f5214c43ec, waiting for CI …

**Pull request merged**
