### PR TITLE
Update references to oldstyle nix run

### PR DESCRIPTION
**Pull request by Riscky**
title says all

### CODE REVIEW

**Review by HugoPeters1024 — APPROVED** [review]
LGTM

**Review by DiegoDiverio — APPROVED** [review]
Just a nit because I stumbled upon it.

**Comment by Riscky** [comment]
@OpsBotPrime merge

**Comment by OpsBotPrime** [comment]
Pull request approved for merge by @Riscky, rebasing now.

**Comment by OpsBotPrime** [comment]
Rebased as 46fbf54a0ae32d2ba0c5c3ab906620a044d7e8d4, waiting for CI …

**Comment by OpsBotPrime** [comment]
[CI job :yellow_circle:](https://channable.semaphoreci.com/workflows/b70fc437-1e56-4e88-9232-090755b80d74?pipeline_id=36c275b5-0d2e-4d72-9492-d8cbbc352da7) started.

**Pull request merged**
