### PR TITLE
Document known issue #147 on readme.md

### PR DESCRIPTION
**Pull request by rudymatela**
Closes: #147

Document known issue #147 on readme.md.  Please see [the relevant section there](https://github.com/channable/hoff/tree/fix/document-known-issue-147#multiple-ci-job-started-comments-147).

### CODE REVIEW

**Comment by rudymatela** [comment]
Other possible fixes not mentioned on the readme:

* keep a list of all URLs sent by GitHub:
    * report each as they arrive; OR
    * update the comment sent by Hoff with the list OR
    * report each as they arrive with a count.

But I think the added complication is not a worthwhile solution...

**Comment by rudymatela** [comment]
@alex-mckenna or @frank-channable, this PR documents a known issue in the README.  Can either of you please review?

**Review by alex-mckenna — APPROVED** [review]
LGTM

**Comment by rudymatela** [comment]
@OpsBotPrime merge

**Comment by OpsBotPrime** [comment]
Your merge request has been denied, because merging on Fridays is not recommended. To override this behaviour use the command `merge on Friday`.

**Comment by rudymatela** [comment]
@OpsBotPrime merge on Friday as this is just documentation...

**Comment by OpsBotPrime** [comment]
Pull request approved for merge by @rudymatela, rebasing now.

**Comment by OpsBotPrime** [comment]
Rebased as af6f23f5c9bc1f95975eaf096c90c72c966e5284, waiting for CI …

**Comment by OpsBotPrime** [comment]
[CI job](https://channable.semaphoreci.com/workflows/df3b78d0-8156-493b-bcae-c2d5dfec1276?pipeline_id=8d69aa21-7a31-4ed7-9665-f98be529245a) started.

**Pull request merged**
