### PR TITLE
Split parsing into a new module

### PR DESCRIPTION
**Pull request by alex-mckenna**
Some initial clean-up before coming back to make a better attempt at parsing subproject commands. The parser should _not_ live amongst the core logic, since it is an entirely separate concern. As a bonus, I moved tests which are to do with parsing into a new test module.

### CODE REVIEW

**Comment by alex-mckenna** [comment]
@OpsBotPrime merge

**Comment by OpsBotPrime** [comment]
Pull request approved for merge by @alex-mckenna, rebasing now.

**Comment by OpsBotPrime** [comment]
Rebased as 8b242f0a064c28a37bd0da2b3d572873ec5123fe, waiting for CI …

**Comment by OpsBotPrime** [comment]
[CI job :yellow_circle:](https://channable.semaphoreci.com/workflows/884299dc-faba-4ac4-826b-2824a5f3ea2c?pipeline_id=da831b38-b68f-410f-9df6-52b952796eb2) started.

**Pull request merged**
