### PR TITLE
Do not retry failed PRs in case of a high priority merge

### LINKED ISSUE #263: Do not retry failed PRs when queuing a high priority merge
Currently, when a PR with high priority is queued, hoff will set the status of all integrated PRs to `NotIntegrated`. This, however, means that also failed PRs are also retried in this case. We should however only set PRs that are part of the merge train to `NotIntegrated`. This is only the PRs that are not failed or failed speculatively behind another PR.

### PR DESCRIPTION
**Pull request by musicismyalibi**
Changes the high priority logic to not retry failed PRs.
Resolves #263

### CODE REVIEW

**Comment by fatho** [comment]
@alex-mckenna @musicismyalibi What's the status here?

**Comment by musicismyalibi** [comment]
@OpsBotPrime merge

**Comment by OpsBotPrime** [comment]
Pull request approved for merge by @musicismyalibi, rebasing now.

**Comment by OpsBotPrime** [comment]
Rebased as 2a701f545535bd624e24d79a3685682190988dec, waiting for CI …

**Comment by OpsBotPrime** [comment]
[CI job :yellow_circle:](https://channable.semaphoreci.com/workflows/3816b8bb-ce4e-42c8-b662-6c33f6bbd6ff?pipeline_id=b3a46a5f-bec9-40e2-af7c-2dbf2152a791) started.

**Comment by OpsBotPrime** [comment]
The [build failed :x:](https://channable.semaphoreci.com/workflows/3816b8bb-ce4e-42c8-b662-6c33f6bbd6ff?pipeline_id=b3a46a5f-bec9-40e2-af7c-2dbf2152a791).

If this is the result of a flaky test, then tag me again with the `retry` command.  Otherwise, push a new commit and tag me again.

**Comment by musicismyalibi** [comment]
@OpsBotPrime retry

**Comment by OpsBotPrime** [comment]
Pull request approved for merge by @musicismyalibi (retried by @musicismyalibi), rebasing now.

**Comment by OpsBotPrime** [comment]
Rebased as ba4a69bfe364b702215b1a9180c50abae723f3c4, waiting for CI …

**Comment by OpsBotPrime** [comment]
[CI job :yellow_circle:](https://channable.semaphoreci.com/workflows/ed691bc7-2a9c-4960-89d8-fd56480b3998?pipeline_id=0b193670-112e-4fcb-afa7-295efe604c49) started.

**Pull request merged**
