### PR TITLE
CI: move to Ubuntu 20.04

### PR DESCRIPTION
**Pull request by rodrigol-chan**
This PR updates the CI pipeline to use Ubuntu 20.04. In addition, it configures Nix to use all cores to build derivations.

### CODE REVIEW

**Review by rudymatela — APPROVED** [review]
LGTM!

**Comment by rudymatela** [comment]
And the build times were reduced to just 2 minutes!  (At least for the last build.)  Awesome!

**Comment by OpsBotPrime** [comment]
Pull request approved for merge by @rodrigol-chan, rebasing now.

**Comment by OpsBotPrime** [comment]
Rebased as 307433d8d74560d2c5b7570da7be9ca8ae0a3108, waiting for CI …

**Comment by OpsBotPrime** [comment]
[CI job :yellow_circle:](https://channable.semaphoreci.com/workflows/b768529a-d874-41b3-a3dd-4c0c7403a173?pipeline_id=84a802fc-ba19-41f5-8869-e950f65ba671) started.

**Pull request merged**
