### PR TITLE
Fix text message during speculative rebase to avoid cross-references between PRs.

### PR DESCRIPTION
**Pull request by DiegoDiverio**
Related to issue https://github.com/channable/hoff/issues/189.

### CODE REVIEW

**Review by fatho — APPROVED** [review]
:shipit:

**Comment by DiegoDiverio** [comment]
@OpsBotPrime merge

**Comment by OpsBotPrime** [comment]
Pull request approved for merge by @DiegoDiverio, rebasing now.

**Comment by OpsBotPrime** [comment]
Rebased as 369769453826d0ca2e885324796c3b3fd6a6ce98, waiting for CI …

**Comment by OpsBotPrime** [comment]
[CI job :yellow_circle:](https://channable.semaphoreci.com/workflows/72cc3f3f-e897-4248-9538-fabec5758b2f?pipeline_id=118b85af-9176-40b2-ab05-f3ad96277b00) started.

**Pull request merged**
