### PR TITLE
Freeze the package versions based on the ones from nixpkgs

### PR DESCRIPTION
**Pull request by robbert-vdh**
This prevents the plain Cabal and the Nix builds from using different versions. This is especially important when using Nix, as Cabal may start using more up to date versions of the package from Hackage if the user has run `cabal update`  before and a local package database exists. Cabal can also be forced to use only the global package registry in which case this problem also doesn't exist, but that requires either breaking non-Nix builds or wrapping the `cabal` command.

I also added the freeze files to the Nix builds so we'll get alerted if nixpkgs gets updated without also updating the freeze file.

### CODE REVIEW

**Review by fatho — APPROVED** [review]

**Comment by robbert-vdh** [comment]
@OpsBotPrime merge

**Comment by OpsBotPrime** [comment]
Pull request approved for merge by @robbert-vdh, rebasing now.

**Comment by OpsBotPrime** [comment]
Rebased as 2cd40a3da62eae63f24edb3c752c4a13c05416cd, waiting for CI …

**Comment by OpsBotPrime** [comment]
[CI job :yellow_circle:](https://channable.semaphoreci.com/workflows/e3a141ec-6810-4bf1-889f-26c286e8035a?pipeline_id=8e58fb6e-6aa5-471f-82c7-3796ea69eed4) started.

**Pull request merged**
