### PR TITLE
Improve build failure markdown comments

### PR DESCRIPTION
**Pull request by rudymatela**
Closes: #151
Closes: #168

------

### Before

> The [build failed :x:](https://example.com)
> If this is the result of a flaky test, close and reopen the PR, then tag me again.
> Otherwise, push a new commit and tag me again.

### After

> The [build failed :x:](https://example.com)
>
> If this is the result of a flaky test, close and reopen the PR, then tag me again.  Otherwise, push a new commit and tag me again.

------

### Before

> Speculative build failed.  I will automatically retry after getting the results of #172.

### After

> Speculative [build failed :x:](https://example.com).  I will automatically retry after getting the results of #172.

------

## Final result

1-white

2-white

1-black

2-black

### CODE REVIEW

**Review by alex-mckenna — APPROVED** [review]

**Comment by rudymatela** [comment]
@alex-mckenna Thanks for the review.

@OpsBotPrime merge

**Comment by OpsBotPrime** [comment]
Pull request approved for merge by @rudymatela, rebasing now.

**Comment by OpsBotPrime** [comment]
Rebased as 900311655b10c3f81c2b390045ebf33da250ddcf, waiting for CI …

**Comment by OpsBotPrime** [comment]
[CI job](https://channable.semaphoreci.com/workflows/4ad4f177-3317-46dd-9d0f-da281141bc77?pipeline_id=f9251621-b8dd-4305-9914-92afe26ab7ec) started.

**Pull request merged**
