### PR TITLE
Hackathon: minor improvements to web interface

### PR DESCRIPTION
**Pull request by tiesjan**
During October 2022's Hackathon I worked on two minor improvements to the Hoff web interface:

- **Reverse order of PRs awaiting approval**
  This was already done in #121, but has been reverted in #178 for unknown reasons. It can still be argued that more recent PRs will be more likely to be merged first.

- **Move PR build info to the secondary info line**
  Adding build info to the first line of a PR (also containing title and id) tends to clutter that line a bit, especially with all the text in primary color orange. It would fit well next to who approved it for merging, as secondary information about that PR.

_Note: not very pressing, but a nice learning exercise._

---

## Before
Screenshot 2022-10-28 at 16-53-47 tiesjan_hoff-test

## After
Screenshot 2022-10-28 at 16-55-31 tiesjan_hoff-test

### CODE REVIEW

**Review by marcin-rzeznicki — APPROVED** [review]
:clap:

**Comment by tiesjan** [comment]
@OpsBotPrime merge away!

**Comment by OpsBotPrime** [comment]
Pull request approved for merge by @tiesjan, rebasing now.

**Comment by OpsBotPrime** [comment]
Rebased as 266379ed8eb44cbe311766ed9f04897cad812623, waiting for CI …

**Comment by OpsBotPrime** [comment]
[CI job :yellow_circle:](https://channable.semaphoreci.com/workflows/cfbfb1c0-c439-4b26-a487-585035d2beea?pipeline_id=45a023e9-d78b-42d8-9f74-00818c436973) started.

**Pull request merged**
