### PR TITLE
Add stack.yaml.lock

### PR DESCRIPTION
**Pull request by duijf**
This was generated by stack when I ran:

    nix run -c stack build

The file helps with reproducibility of builds, so let's track it in the git repo.

### CODE REVIEW

**Comment by duijf** [comment]
Semaphore isn't operational yet -- I added the project in Semaphore, but haven't set up a pipeline definition yet. 

I paused builds on Semaphore for now until we have fully set it up.

**Comment by duijf** [comment]
LGTM 0a5996f

**Comment by duijf** [comment]
LGTM 0a5996f

**Comment by duijf** [comment]
LGTM 0a5996f

**Comment by OpsBotPrime** [comment]
Rebased as 0a5996f6bf41e9f0ef549a1c0f4aeda0b6c690cf, waiting for CI …

**Comment by duijf** [comment]
Hoff will be waiting on CI for this PR for a long time. 

Travis now reports commit build statuses using the GitHub checks API instead of the status API. Hoff does not have support for that yet.

**Comment by duijf** [comment]
I'm merging this one manually, will test on a new PR soon :)

**Pull request merged**
