### PR TITLE
Add a link to the readme when reporting parse errors

### LINKED ISSUE #261: Return short instructions on invalid command, like a CLI
The discoverability of Hoff is inherently limited as it is called using comments. It would however be nice to be somewhat more friendly to users by giving them some instructions when they call Hoff. This is similar to how most CLI tools work.

### PR DESCRIPTION
**Pull request by isomorpheme**
Resolves #261. I've decided to just add a (hard-coded) message linking to the syntax description in the readme; hard-coding a summarised description of the syntax might be nicer, but would essentially be duplication with the readme and risk getting out of sync. Ideally, the syntax description would be extracted from the parser, like what many CLI arg parsing libraries support, but that's not trivial, so leaving it to future work.

### CODE REVIEW

**Review by musicismyalibi — APPROVED** [review]
LGTM. Might be good to create a new issue or keep the issue open to indicate that there is still room for future improvements.

**Comment by isomorpheme** [comment]
@OpsBotPrime merge

**Comment by OpsBotPrime** [comment]
Pull request approved for merge by @isomorpheme, rebasing now.

**Comment by OpsBotPrime** [comment]
Rebased as 7aa6981e82d7e0d930d3b6824c387410f7159bfc, waiting for CI …

**Comment by OpsBotPrime** [comment]
[CI job :yellow_circle:](https://channable.semaphoreci.com/workflows/139d8104-98ab-43fe-932c-27065936bf1a?pipeline_id=001dd641-28b1-4f4e-8ebd-1862e1adc141) started.

**Pull request merged**
