### PR TITLE
add API endpoint to get project status

### PR DESCRIPTION
**Pull request by Riscky**
We want to expose the status of Hoff in an API. This is the most simple way to expose the data we need.

### CODE REVIEW

**Review by HugoPeters1024 — APPROVED** [review]
LGTM

**Comment by Riscky** [comment]
@OpsBotPrime merge

**Comment by OpsBotPrime** [comment]
Pull request approved for merge by @Riscky, rebasing now.

**Comment by OpsBotPrime** [comment]
Rebased as effe3a541fdba6d3a22b7e949fb0bae0c03c1bd3, waiting for CI …

**Comment by OpsBotPrime** [comment]
[CI job :yellow_circle:](https://channable.semaphoreci.com/workflows/13f501e3-40c5-4df5-a65a-e85938f2896d?pipeline_id=8f375f87-3f9e-47f6-8eaa-a1c05d356764) started.

**Pull request merged**
