### PR TITLE
Update hostname of package repository

### PR DESCRIPTION
**Pull request by tomwassenberg**
This makes the shipping step work again when run from CI.

This is necessary, because the IP that `archive.channable.com` resolves to isn't on the public internet any more.

### CODE REVIEW

**Review by ruuda — APPROVED** [review]

**Review by ruuda — APPROVED** [review]
Let’s see if the webhook now works ... @OpsBotPrime merge

**Comment by ruuda** [comment]
Nope, looks like pull request review webhooks aren’t yet being delivered ... @OpsBotPrime merge

**Comment by OpsBotPrime** [comment]
Pull request approved for merge by @ruuda, rebasing now.

**Comment by OpsBotPrime** [comment]
Rebased as adfada24a98ced02c618ffb59fe6516952a8316f, waiting for CI …

**Comment by tomwassenberg** [comment]
It looks like the webhook [did get sent](https://github.com/channable/hoff/settings/hooks/173354708) to Hoff (with iD `6152ff20-7100-11eb-8008-5b39c2a78b1f`), but Hoff returned a 501 to GitHub :thinking:

**Pull request merged**
