### PR TITLE
Improve markdown in comments for ``CI job started`` and ``build failed``

### LINKED ISSUE #151: Comment about build failures with a markdown link
When the build starts :yellow_circle:, Hoff posts [the following message](https://github.com/channable/hoff/pull/148#issuecomment-1205230894):

> [CI job](https://channable.semaphoreci.com/workflows/65d0fd03-ad1a-478f-9e66-94b8f6002f28?pipeline_id=e3e868de-ecdc-41e2-837a-a90125f3d455) started.

When the build fails :x:, Hoff posts the following message:

> The build failed: https://channable.semaphoreci.com/workflows/00000000-0000-0000-0000-000000000000?pipeline_id=00000-00000-00000-0000
> If this is the result of a flaky test, close and reopen the PR, then tag me again.
Otherwise, push a new commit and tag me again.

For build failures, we should do like build starts and use a markdown link for a nicer message:

> The [build failed :x:](https://channable.semaphoreci.com/workflows/00000000-0000-0000-0000-000000000000?pipeline_id=00000-00000-00000-0000).
>
> If this is the result of a flaky test, close and reopen the PR, then tag me again.  Otherwise, push a new commit and tag me again.

... and while we're at it, we may add an `:yellow_circle:` :yellow_circle: to the build started message:

> [CI job :yellow_circle:](https://channable.semaphoreci.com/workflows/65d0fd03-ad1a-478f-9e66-94b8f6002f28?pipeline_id=e3e868de-ecdc-41e2-837a-a90125f3d455) started.

Or maybe:

> [CI job :yellow_circle: started](https://channable.semaphoreci.com/workflows/65d0fd03-ad1a-478f-9e66-94b8f6002f28?pipeline_id=e3e868de-ecdc-41e2-837a-a90125f3d455).

... to make it more consistent with the new build failure message.

### PR DESCRIPTION
**Pull request by DanielNoord**
Closes #151

I ran into various issues trying to test this locally. For example, `stack` assumes `nix` is installed which wasn't listed as a requirement. (Note the _If using Nix_ in the README).
Either way, since this is a fairly trivial markdown change I thought I would still submit the PR.

Let me know if this requires any changes 😄

### CODE REVIEW

**Comment by rudymatela** [comment]
@DanielNoord Thanks for the addition.  :smile:  Tests are passing here.

I will merge this myself later this week after I merge #137.

**Review by rudymatela — APPROVED** [review]

**Comment by rudymatela** [comment]
... I am "assigning" this to me so I don't forget to merge it later.

@DanielNoord I've marked you as an assignee as well, so you can have the clear credits when I merge (feel free to unnasign yourself if you rather it not appear under your main GH issues tab).

**Comment by DanielNoord** [comment]
> ... I am "assigning" this to me so I don't forget to merge it later.
> 
> @DanielNoord I've marked you as an assignee as well, so you can have the clear credits when I merge (feel free to unnasign yourself if you rather it not appear under your main GH issues tab).

Thanks! Wouldn't it show up anyway? My account should appear in the commit tree of the repo right?

**Comment by rudymatela** [comment]
> > @DanielNoord I've marked you as an assignee as well, so you can have the clear credits when I merge (feel free to unnasign yourself if you rather it not appear under your main GH issues tab).
> 
> Thanks! Wouldn't it show up anyway? My account should appear in the commit tree of the repo right?

You're right, it will.  I just wanted to make the credits clearer. :-)

**Comment by rudymatela** [comment]
@OpsBotPrime merge on Friday

**Comment by OpsBotPrime** [comment]
Pull request approved for merge by @rudymatela, waiting for rebase behind 2 pull requests.

**Comment by OpsBotPrime** [comment]
Failed to rebase, please rebase manually using

    git rebase --interactive --autosquash origin/master markdown-comment

**Comment by rudymatela** [comment]
@OpsBotPrime merge on Friday

**Comment by OpsBotPrime** [comment]
Pull request approved for merge by @rudymatela, rebasing now.

**Comment by OpsBotPrime** [comment]
Rebased as e02641febb60c7b26b1aacf2fba7696dce18aa68, waiting for CI …

**Comment by OpsBotPrime** [comment]
[CI job](https://channable.semaphoreci.com/workflows/42aec48b-aa15-4d65-89b2-d6dd9168d51b?pipeline_id=c6cee156-e976-48d8-8876-14560475eeb7) started.

**Comment by DanielNoord** [comment]
@rudymatela Not sure if this due to the recent merge train change, but this PR seems to have been merged to `main` but hasn't been closed. Should I just close it?

**Comment by rudymatela** [comment]
> @rudymatela Not sure if this due to the recent merge train change, but this PR seems to have been merged to `main` but hasn't been closed. Should I just close it?

I will close it now.

I don't think this is related to the merge trains change.  Usually GitHub closes PRs automatically when they are merged into the main branch.  In this case, it failed to detect that the branch was merged because it was from a different remote repository.

I think that this issue has always been present with Hoff... Perhaps when it detects the branch is from a different remote, it should post a comment stating that the PR has been merged but that it should be closed manually, or something else appropriate.  I will create an issue soon when I have the time and link it here.

**Comment by rudymatela** [comment]
This is a merge train example.  https://github.com/channable/hoff/issues/160
(Never mind this comment.  I am just gathering a list to analyse.)

**Pull request closed without merging**
