### PR TITLE
Allow extra whitespace in merge commands

### PR DESCRIPTION
**Pull request by ReinierMaas**
XRef: https://github.com/channable/hoff/issues/102

> it might also be more user-friendly to accept one or more spaces between the mention and the command instead of just one. ~ Riley

Yes, that is definitely more user-friendly!

---

Allowing extra whitespace in the merge commands to overcome the (somewhat) common double whitespace.

### CODE REVIEW

**Review by RileyApeldoorn — APPROVED** [review]
Looks good! I left a small idea for improvement, but it's nothing critical so feel free to disregard it :)

**Comment by ReinierMaas** [comment]
@OpsBotPrime merge!

**Comment by OpsBotPrime** [comment]
Your merge request has been denied, because merging on Fridays is not recommended. To override this behaviour use the command `merge on Friday`.

**Comment by ReinierMaas** [comment]
@OpsBotPrime merge!

**Comment by OpsBotPrime** [comment]
Pull request approved for merge by @ReinierMaas, rebasing now.

**Comment by OpsBotPrime** [comment]
Rebased as 6f1b2a3da30af3227d6d4f6e163fd95c5618ffeb, waiting for CI …

**Comment by OpsBotPrime** [comment]
Abandoning this pull request because it was closed.

**Comment by bertptrs** [comment]
@OpsBotPrime merge and for real this time.

@ReinierMaas the CI was never started due to Semaphore issues, I'll retry this for you.

**Comment by OpsBotPrime** [comment]
Pull request approved for merge by @bertptrs, rebasing now.

**Comment by OpsBotPrime** [comment]
Rebased as 8cc81f5579c333feaeba0fe0a1f7b4faf1285c3b, waiting for CI …

**Pull request merged**
