### PR TITLE
Do not unintegrate after a failing pull request is closed

### PR DESCRIPTION
**Pull request by rudymatela**
closes: #184

### CODE REVIEW

**Review by alter2000 — APPROVED** [review]
```
╻  ┏━╸╺┳╸┏┳┓
┃  ┃╺┓ ┃ ┃┃┃
┗━╸┗━┛ ╹ ╹ ╹
```

Thanks for the comment amend!

**Comment by rudymatela** [comment]
@alter2000 Thanks for the speedy review!  :-D

@OpsBotPrime merge on Friday this is a bugfix anyway.

**Comment by OpsBotPrime** [comment]
Pull request approved for merge by @rudymatela, rebasing now.

**Comment by OpsBotPrime** [comment]
Rebased as 5d937cf961deeee883ea9d1180eb8fab17f00b89, waiting for CI …

**Comment by OpsBotPrime** [comment]
[CI job :yellow_circle:](https://channable.semaphoreci.com/workflows/8047ece3-cee2-48c4-b50f-dad879353f74?pipeline_id=781f7480-f871-413f-a66c-43bacb04198e) started.

**Pull request merged**
