### PR TITLE
feedbackOnStatus: Use format for everything

### PR DESCRIPTION
**Pull request by isomorpheme**
Depends on #272 (just because that function got touched there; rebasing later would be a pain).

### CODE REVIEW

**Comment by robbert-vdh** [comment]
Just FYI, `Text.Format` is a big footgun, and I'd avoid it for anything somehwat mission critical (or in general). If the length o the list doesn't match the number of placeholders, then this call will diverge, which could end up taking the entire service down.

**Comment by isomorpheme** [comment]
> Just FYI, `Text.Format` is a big footgun, and I'd avoid it for anything somehwat mission critical (or in general). If the length o the list doesn't match the number of placeholders, then this call will diverge, which could end up taking the entire service down.

Thanks for pointing this out! I've created #275 to completely get rid of it then.

**Comment by isomorpheme** [comment]
@OpsBotPrime merge

**Comment by OpsBotPrime** [comment]
Pull request approved for merge by @isomorpheme, rebasing now.

**Comment by OpsBotPrime** [comment]
Failed to rebase, please rebase manually using

    git fetch && git rebase --interactive --autosquash origin/master refactor-use-format

**Comment by isomorpheme** [comment]
@OpsBotPrime merge

**Comment by OpsBotPrime** [comment]
Rebased as 82ebfd6dc13005fd8556167221990657730f94ee, waiting for CI …

**Comment by OpsBotPrime** [comment]
[CI job :yellow_circle:](https://channable.semaphoreci.com/workflows/1ba5ef98-cb20-413a-8d1f-ebe90510b8a8?pipeline_id=3e339b5e-aa14-4c37-aa0c-750289a92dfc) started.

**Pull request merged**
