### PR TITLE
Use a proper class and fix version rendering

### PR DESCRIPTION
**Pull request by rudymatela**
Closes: #175 

fix

### CODE REVIEW

**Comment by rudymatela** [comment]
@RileyApeldoorn and @alter2000 can either of you please review?

Thanks again for helping me troubleshoot this.  Much appreciated.  :smile:

**Review by alter2000 — APPROVED** [review]
<3

**Comment by rudymatela** [comment]
@alter2000 Thanks for the review!

@OpsBotPrime merge!

**Comment by OpsBotPrime** [comment]
Pull request approved for merge by @rudymatela, waiting for rebase behind one pull request.

**Comment by OpsBotPrime** [comment]
Speculatively rebased as 8caf09a8fd4f88b029bdc1e9fd558367d9683f92 behind #174, waiting for CI …

**Comment by OpsBotPrime** [comment]
[CI job :yellow_circle:](https://channable.semaphoreci.com/workflows/e13aec10-9b26-4cf9-86b5-c9a2e0ce968e?pipeline_id=7eb8e940-160e-480e-b99a-24d555fb578e) started.

**Pull request merged**
