### PR TITLE
Remember previously merged PRs for detecting pushes to master

### PR DESCRIPTION
**Pull request by musicismyalibi**
Adds an extra list to the state with recently merged PRs. When detecting a push to master we use this list to check if the push is from merging one of the known PRs.

### CODE REVIEW

**Review by fatho — APPROVED** [review]
LGTM!

**Comment by musicismyalibi** [comment]
@OpsBotPrime merge

**Comment by HoffBotPrime** [comment]
Rebased as e163a285993ad723be9be15bc792371ce449f161, waiting for CI …

**Comment by HoffBotPrime** [comment]
[CI job :yellow_circle:](https://channable.semaphoreci.com/workflows/f6b7a772-e862-4c23-92e6-fb2d75f53cc3?pipeline_id=4080494c-1649-42ab-805b-9acd8e213a0f) started.

**Pull request merged**
