### PR TITLE
Change approval syntax from "LGTM <sha>" to "@bot merge"

### LINKED ISSUE #2: Remove the need to provide the commit hash in merge comment
The current syntax for approving a PR and getting it merged is `LGTM <hash>`, where the hash must match the tip of the PR. That is good to ensure that what you approve is what you reviewed, but unfortunately the Github UI orders commits by date instead of by topological order, so figuring out the hash from the webinterface is not always trivial. Also, copying the hash from the webinterface is difficult.

We should change the syntax to `@bot merge`. This means we need to know the username of the bot too in the config.

### PR DESCRIPTION
**Pull request by ruuda**
Closes #2.

* Add a new configuration option, `trigger.commentPrefix` to choose a prefix that triggers the bot. It should be configurable because it is nice to set it to the username of the bot, so you can say “@bot merge”.
* The configuration is a nested object because the parser is just a derived `FromJSON`, and it is a bit nicer to pass just the necessary configuration to the application logic, and not the full config including secrets and unrelated values.
* Update the approval check to no longer care about the commit hash, but check for the prefix instead.
* Update tests and docs.

### CODE REVIEW

**Comment by ruuda** [comment]
> What happens in case someone enters @hoffbot<space><space>merge in a GitHub comment (so with two space characters)?

Then you hit the second branch: https://github.com/channable/hoff/blob/58ef0a92f47b1bfc08383ef9a83e031c76758134/src/Logic.hs#L260-L261

And then nothing happens, the comment is ignored because it is not a merge command.

> Should we make the bot user post something when the command is not understood, but does start with the prefix?

I think that after we implement #11, this will be less of an issue; the lack of feedback would then mean that something is up. Let’s see how it goes first, and if it is an issue in practice.

**Comment by ruuda** [comment]
LGTM 58ef0a9

**Comment by OpsBotPrime** [comment]
Failed to rebase, please rebase manually.

**Comment by ruuda** [comment]
LGTM 753be06

**Comment by OpsBotPrime** [comment]
Failed to rebase, please rebase manually.

**Comment by ruuda** [comment]
LGTM a0d0bc1

**Comment by OpsBotPrime** [comment]
Rebased as 985e3763db6175fc48a5babb5393e65e85625309, waiting for CI …

**Pull request merged**
