### PR TITLE
Update `nixpkgs`

### PR DESCRIPTION
**Pull request by pbrinkmeier**
Hiya, I'd like to work on #236 and perhaps #159. For default values in the config, it would be cool to have access to [`Data.Aeson.omittedField`](https://hackage.haskell.org/package/aeson-2.2.1.0/docs/Data-Aeson.html#v:omittedField), which was only added recently.

So this PR bumps `nixpkgs` to the most recent ref at the time of writing.

NB the ref contains `aeson_2_2_1_0` which can be used for this purpose, but not yet for overriding `aeson` in the overlay. This means that after bumping `nixpkgs`, the closure of `hoff` would contain multiple versions of `aeson` which would have to be resolved at some later point in time.

The PR also replaces the occurrences of the deprecated Scotty action `param` with `captureParam` because it wouldn't build otherwise with newer versions of Scotty due to the deprecation warnings and `-Werror`.

### CODE REVIEW

**Review by FPtje — APPROVED** [review]
Thanks a lot for the nixpkgs update! I can imagine the Hoff nixpkgs was out of date by quite a bit.

I see that CI isn't running. Maybe asking Hoff to merge this PR kicks CI into action.

@OpsBotPrime merge

**Comment by OpsBotPrime** [comment]
Pull request approved for merge by @FPtje, rebasing now.

**Comment by OpsBotPrime** [comment]
Rebased as 646154aad0afb30d21ad0ebf09cad7f371e37adb, waiting for CI …

**Comment by OpsBotPrime** [comment]
[CI job :yellow_circle:](https://channable.semaphoreci.com/workflows/a43ccaeb-6de0-4c97-85ae-590022eeec71?pipeline_id=c57852fc-bde6-4b69-a63a-5784af66ac40) started.

**Pull request merged**
