### PR TITLE
Add "merge and deploy" command

### PR DESCRIPTION
**Pull request by maartenberg**
This PR adds a new command "{prefix} merge and deploy" to Hoff.
This command also approves a PR for rebase and merge, and currently triggers the same merge behaviour as "{prefix} merge".

Changes:
  - A new value `MergeAndDeploy` is added to `ApprovedFor`.
  - `parseMergeCommand` now searches for the "{prefix} merge and deploy" infix before searching for "{prefix} merge", returning `Just MergeAndDeploy` if found.
  - The web interface will show which merge command was used to approve a PR:
    - Approved PRs show the text "Approved by {user}" in the current version of Hoff,
    - PRs approved with "{prefix} merge and deploy" now show "Approved for merge and deploy by {user}",
    - PRs approved with "{prefix} merge" now show "Approved for merge by {user}".
  - The approval acknowledgement message now echoes the command that was used to approve the PR, i.e. Hoff will comment "Pull request was approved (for merge | for merge and deploy) by {user}, …" depending on which command was used.
  - The tests were updated to adjust to the new expected messages and to include a use of "merge and deploy" in the testcases.

### CODE REVIEW

**Review by rkrzr — APPROVED** [review]
Nice and compact change :+1:

**Comment by maartenberg** [comment]
@OpsBotPrime merge

**Comment by OpsBotPrime** [comment]
Pull request approved by @maartenberg, rebasing now.

**Comment by OpsBotPrime** [comment]
Rebased as 5364d96a5bc16a1fcd6b05231924dd5fc7f7450e, waiting for CI …

**Pull request merged**
