### PR TITLE
Updated build failed message

### LINKED ISSUE #24: Include link to build logs in "build failed" comment
When the build fails, the bot user will leave a comment that states that. But because the build was for the `testing` branch, and not for the pull request branch, there is no single-click way to get from the pull request page to the build logs.

I suspect GitHub will include a detail url with the build status webhook. We can store it, and include it in the comment.

### PR DESCRIPTION
**Pull request by Riscky**
Updated the build failed message with an url to the build failure (if provided by github)
This closes #24

### CODE REVIEW

**Review by maartenberg — APPROVED** [review]
LGTM!

**Comment by Riscky** [comment]
@OpsBotPrime merge

**Comment by OpsBotPrime** [comment]
Pull request approved for merge by @Riscky, rebasing now.

**Comment by OpsBotPrime** [comment]
Rebased as 32d16198e4eadc0bab1acbefa4886b95853eb44b, waiting for CI …

**Pull request merged**
