### PR TITLE
Prevent feedback loops through parser errors

### LINKED ISSUE #223: Hoff responds to its own messages when it repeats the command in a parser failure message
#219 changes the parser to be stricter and have better error reporting. Problem is that Hoff is also configured to reply to its respond to its own messages so it can automate itself. As a result, if will end up in a feedback loop where it parses the command in the error message and then posts another error message.

One way to fix this would be to omit the repetition of the original message in the error message. I think this feedback is actually pretty nice though, and I'd prefer a solution where that is kept in tact. I'd propose adding something like a `<!-- Hoff: ignore -->` token that would prevent the parser from parsing the comment for commands. Then error messages can contain any text with no repercussions (and error messages with suggestions for commands could then also safely contain the prefix). I'll look into this soon.

### PR DESCRIPTION
**Pull request by robbert-vdh**
The new parser repeats part of the comment in its error messages so it can highlight the syntax error. This is great, except for the fact that in production the comment posted by Hoff also comes in as a webhook event. And since the error message contains the repeated merge command, Hoff would enter a feedback loop where it complains about parsing errors in its own comments. The tests now also simulate this webhook event to make sure this doesn't happen again.

Hoff being able to respond to itself is a feature since it's used to automate deployments in certain repositories. This approach uses a simple HTML comment that is added to parser error messages. If the comment is found in any message, Hoff won't try to parse it for commands. This is also useful in other situations where Hoff may post arbitrary output that could contain its command prefix.

This fixes #223.

### CODE REVIEW

**Review by crtschin — APPROVED** [review]
LGTM!

**Comment by robbert-vdh** [comment]
Thanks for the review! @OpsBotPrime merge

**Comment by OpsBotPrime** [comment]
Pull request approved for merge by @robbert-vdh, rebasing now.

**Comment by OpsBotPrime** [comment]
[CI job :yellow_circle:](https://channable.semaphoreci.com/workflows/7c174981-c5c4-4808-bb60-de99746ae825?pipeline_id=a1ca27a8-7955-4f4b-ba7b-d87a02f80708) started.

**Pull request merged**
