### PR TITLE
ci: machine type from e1 to f1

### PR DESCRIPTION
**Pull request by d-goncalves**

### CODE REVIEW

**Comment by d-goncalves** [comment]
@OpsBotPrime merge

**Comment by OpsBotPrime** [comment]
Pull request approved for merge by @d-goncalves, rebasing now.

**Comment by OpsBotPrime** [comment]
Rebased as 4e97ba26edbbdd268971e7c7eae4c9d5ce00489e, waiting for CI …

**Comment by OpsBotPrime** [comment]
[CI job :yellow_circle:](https://channable.semaphoreci.com/workflows/68fdf93d-6b34-4ca3-bc12-d81f9f516769?pipeline_id=fdebfd87-2167-4828-9dc6-195015c75e6a) started.

**Pull request merged**
