### PR TITLE
Ignore duplicate build status webhooks

### PR DESCRIPTION
**Pull request by rudymatela**
Closes: #144

Ignore duplicate build status webhooks.

### CODE REVIEW

**Comment by rudymatela** [comment]
Since this one is somewhat urgent / somewhat of a hotfix, I've tagged three people to review.  I'll merge after I get one approval.

**Review by RileyApeldoorn — APPROVED** [review]
:+1:

**Comment by rudymatela** [comment]
@RileyApeldoorn Awesome, thanks for the review.  I am merging now to have the fix ready for deployment soon.

@OpsBotPrime merge

**Comment by OpsBotPrime** [comment]
Pull request approved for merge by @rudymatela, rebasing now.

**Comment by OpsBotPrime** [comment]
Rebased as 8e2ec1ec6dcc3e252f6c0ebb6617affc9c434e75, waiting for CI …

**Comment by OpsBotPrime** [comment]
Waiting on CI job: https://channable.semaphoreci.com/workflows/c96f22ef-1555-475f-8a29-86e48985bf8e?pipeline_id=f215f0e1-041a-4917-9f99-665a9f84bc2b

**Pull request merged**
